apt update && apt install curl sudo wget -y
curl -sSL https://get.docker.com/ | sh
sudo apt-get install docker-compose -y

# autobot
version: "2.0"
services:
  bot:
    image: python:3.8
    container_name: bot
    restart: always
    tty: true
    network_mode: bridge
    hostname: bot
    volumes:
      - /home/saint:/home

# qb
version: "2.1"
services:
  qb:
    image: linuxserver/qbittorrent
    container_name: qb
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
      - WEBUI_PORT=8080
    volumes:
      - /home/qb/config:/config
      - /home/qb/downloads:/downloads
      - /home/qb/config/rclone:/root/.config/rclone
    ports:
      - 55555:55555
      - 6881:6881/udp
      - 8080:8080
    network_mode: bridge
    restart: unless-stopped
    
# Aria2系列
version: "3.3"
services:
  aria2:
    image: p3terx/aria2-pro
    container_name: aria2
    environment:
      - PUID=0
      - PGID=0
      - UMASK_SET=022
      - RPC_SECRET=<key>
      - RPC_PORT=6800
      - LISTEN_PORT=6888
      - DISK_CACHE=64M
      - IPV6_MODE=false
      - UPDATE_TRACKERS=true
      - CUSTOM_TRACKER_URL=
      - TZ=Asia/Shanghai
      - SPECIAL_MODE=rclone
    volumes:
      - /home/aria2/config:/config
      - /home/aria2/downloads:/downloads
    ports:
      - 6800:6800
      - 6888:6888
    network_mode: host
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: 1m

  AriaNg:
    image: p3terx/ariang
    container_name: ariang
    command: --port 6880 --ipv6
    network_mode: host
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: 1m

  Aria2Bot:
    image: p3terx/tele-aria2:0.2.2
    container_name: aria2bot
    volumes:
      - /home/aria2/.tele-aria2-conf.json:/config.json
    network_mode: host
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: 1m


# librespeed
docker run -d \
  --name=librespeed \
  -e PUID=1000 \
  -e PGID=1000 \
  -e TZ=Asia/Shanghai \
  -e PASSWORD=password \
  -p 7788:80 \
  -v /root/ls/config:/config \
  --restart always \
  ghcr.io/linuxserver/librespeed
  
